### ISSUE TITLE
Fix flaky tests

### ISSUE THREAD

**Issue by LeonBein** [bptlab/scylla#58]
Some tests have shown to be flaky (i.e. failing non-deterministically).
The following were identified:

- [x] SequentialTaskbasedTests.testActivitiesAreSequentialWithResources:64->BatchSimulationTest.runSimpleSimulation:33->SimulationTest.runSimpleSimulation:53 » NullPointer
- [x] ParallelTests.testCasesAreParallelWithResources:52->BatchSimulationTest.runSimpleSimulation:33->SimulationTest.runSimpleSimulation:53 » NullPointer

**Comment by LeonBein** [comment]
Actual error might be in Statisticslogger:103 because detailed error message states `java.lang.NullPointerException: Cannot invoke "de.hpi.bpt.scylla.simulation.ResourceObject.getTimetable()" because the return value of "java.util.Map.get(Object)" is null` and this is the only place getTimetable is run on a result of Map.get

**Comment by LeonBein** [comment]
Potential real root cause

> Exception in thread "proceed" java.lang.NullPointerException: Cannot invoke "de.hpi.bpt.scylla.simulation.ResourceObjectTuple.getResourceObjects()" because the return value of "java.util.Map.get(Object)" is null
> 	at de.hpi.bpt.scylla.simulation.event.TaskTerminateEvent.addToLog(TaskTerminateEvent.java:128)
> 	at de.hpi.bpt.scylla.simulation.event.TaskEvent.eventRoutine(TaskEvent.java:30)
> 	at de.hpi.bpt.scylla.simulation.event.TaskTerminateEvent.eventRoutine(TaskTerminateEvent.java:40)
> 	at de.hpi.bpt.scylla.simulation.event.TaskTerminateEvent.eventRoutine(TaskTerminateEvent.java:31)
> 	at desmoj.core.simulator.Scheduler.processNextEventNote(Unknown Source)
> 	at desmoj.core.simulator.Experiment.doProceed(Unknown Source)
> 	at desmoj.core.simulator.Experiment.access$000(Unknown Source)
> 	at desmoj.core.simulator.Experiment$2.run(Unknown Source)
> 	at co.paralleluniverse.strands.Strand$SuspendableRunnableRunnable.run(Strand.java:825)
> 	at java.base/java.lang.Thread.run(Thread.java:1623)

**Comment by LeonBein** [comment]
Analyzing the trace shows that in some cases, a batch cluster is enabled twice
