### ISSUE TITLE
Running Mooc Example from Console throws Error in XESLogger

### ISSUE THREAD

**Issue by LeonBein** [bptlab/scylla#71]
When downloading and extracting the scylla.jar,
and running the Mooc example (regular event configuration),
the following error occurs:

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "java.util.Map.keySet()" because "nodeInfos" is null
        at de.hpi.bpt.scylla.plugin.xeslogger.XESLogger.writeToLog(XESLogger.java:95)
        at de.hpi.bpt.scylla.plugin_type.logger.OutputLoggerPluggable.runPlugins(OutputLoggerPluggable.java:39)
        at de.hpi.bpt.scylla.SimulationManager.run(SimulationManager.java:186)
        at de.hpi.bpt.scylla.Scylla.main(Scylla.java:77)
```

**Comment by LeonBein** [comment]
This error appears to not occur when running from IDE ...

**Comment by LeonBein** [comment]
Consider this for #73 , remove BPS flag in favor of proper plugin configuration
