### ISSUE TITLE
Can't execute a scenario which requires the StatisticsLogger

### ISSUE THREAD

**Issue by marcfreiheit** [bptlab/scylla#9]
I'm currently running into problems when I try to run the p7_dmn scenario with your latest code. I've included both jar libraries into the project. 

I'm trying to run this setup:
```java
public class Scylla {

    public static final String OS = System.getProperty("os.name");
    public static final String FILEDELIM = (OS.contains("Linux") || OS.contains("Mac OS")) ? "/" : "\\";

    public static void main(String[] args) {

        String folder = "samples" + FILEDELIM;
        String resFilename = folder + "p0_globalconf_without.xml";

        String[] bpmnFilename = new String[] { folder + "p7_dmn.bpmn" };
        String[] simFilenames = new String[] { folder + "p7_dmn_sim.xml" };

        boolean enableBpsLogging = true;
        boolean enableDesmojLogging = false;

        SimulationManager manager = new SimulationManager(folder, bpmnFilename, simFilenames, resFilename,
                enableBpsLogging, enableDesmojLogging);
        manager.run();
    }

}
```

The requested directory `samples/output_17_11_30_15_46_11/samples/` does not exist. There is just an empty `output_17_11_30_15_46_11/` directory.

Stack trace of error: 
```
java.io.FileNotFoundException: samples/output_17_11_30_15_46_11/samples/p0_globalconf_without_resourceutilization.txt (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:192)
	at java.io.PrintWriter.<init>(PrintWriter.java:232)
	at de.hpi.bpt.scylla.plugin.statslogger.StatisticsLogger.writeToLog(StatisticsLogger.java:370)
	at de.hpi.bpt.scylla.plugin_type.logger.OutputLoggerPluggable.runPlugins(OutputLoggerPluggable.java:38)
	at de.hpi.bpt.scylla.SimulationManager.run(SimulationManager.java:231)
	at de.hpi.bpt.scylla.Scylla.main(Scylla.java:98)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

You've got an idea? I'm stuck on this issue.

**Comment by LeonBein** [comment]
Hi Marc, it seems that there is a general issue with the source path that is given rather than one with the p7 scenario. Which branch are you using? Did it work using the UI?

**Comment by marcfreiheit** [comment]
Hey! I've checked out your latest code on `dev_ui` and ran `Scylla.java`. 

When running it using the GUI I'm getting a similar output:

```
java.io.FileNotFoundException: /Users/marc/Documents/Development/GitHub/scylla/samples/output_17_12_01_13_02_35/Users/marc/Documents/Development/GitHub/scylla/samples/p0_globalconf_Notfallstation_resourceutilization.txt (No such file or directory)
at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at java.io.PrintWriter.<init>(PrintWriter.java:192)
	at java.io.PrintWriter.<init>(PrintWriter.java:232)
	at de.hpi.bpt.scylla.plugin.statslogger.StatisticsLogger.writeToLog(StatisticsLogger.java:370)
	at de.hpi.bpt.scylla.plugin_type.logger.OutputLoggerPluggable.runPlugins(OutputLoggerPluggable.java:38)
	at de.hpi.bpt.scylla.SimulationManager.run(SimulationManager.java:231)
	at de.hpi.bpt.scylla.GUI.SimulationPane.SimulationPane.startSimulation(SimulationPane.java:585)
	at de.hpi.bpt.scylla.GUI.SimulationPane.SimulationPane.access$6(SimulationPane.java:564)
	at de.hpi.bpt.scylla.GUI.SimulationPane.SimulationPane$7.actionPerformed(SimulationPane.java:431)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by LeonBein** [comment]
Hm, it seems the error comes from SimulationManager class, Line 113, where the "fileNameWithoutExtension" is not set correctly due to platform specific file path delimiters. I hopefully fixed the line and commited the change, please try if it works now.

**Comment by marcfreiheit** [comment]
Nope. Didin't work. Same error.

**Comment by LeonBein** [comment]
Fixed by Björn, wrong file delim.
